# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SSLiveStreaming' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SSLiveStreaming

  pod 'SQLite.swift', '~> 0.12.0'
    pod 'AFNetworking', '3.1.0'
    pod 'JXCategoryView', '1.4.0'
    pod 'JXPagingView/Paging'
    pod 'ObjectMapper', '3.4.2'
    #pod 'DeviceKit', '~> 2.1.0'
    pod 'SnapKit', '4.2.0'
    pod 'Result', '4.1.0'
    pod 'IQKeyboardManagerSwift'
    
    pod 'RxSwift'             # 函数式库
    pod 'RxCocoa'             # cocoa扩展
    pod 'Moya/RxSwift'        # rxw化的网络库
    pod 'NSObject+Rx'         # 便捷实用RXSwift
    pod 'Then'                # 语法糖
    pod 'CWLateralSlide', '~> 1.6.3'
    
end
